# <code style="background:yellow;color:black">Summary:</code>

1. Brief about Data Analysis and Visualization (DAV)
2. What is numpy?
3. Python lists are heterogenous. Numpy only handles homogenous data.
4. Creating 1D and 2D numpy arrays using array() method from python list and using arange() method. Difference between arange() and array(range()) methods.
5. ndim and shape attribute of numpy array object.
6. Numpy arrays support element wise operations.
7. New function to check execution time of a particular operation.
8. Why is numpy so fast?
9. Indexing and Slicing in Numpy- Basic and Fancy indexing (masking).
10. Everything in python is an object. In a NumPy array, all subarrays (rows) should have the same length. Visualization of 3D array in notes.
11. Typecasting
12. NPS case study

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Data Analysis and Visualization (DAV):</code>

This entire DAV section of the course is divided into three parts:
1. DAV-1 - Python libraries - Time to complete - 1 month and 1 week
2. DAV-2 - Probability and Statistics
3. DAV-3 - Hypothesis Testing

DAV-2 and 3 in total will take 2 to 2.5 months to complete.

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">What is Numpy:</code>

**NumPy, which stands for "Numerical Python," is a fundamental Python library for numerical and scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on these arrays. NumPy is a free and open-source library, and is available for download from the NumPy website.**

**<u>Here are some of the primary use cases for NumPy:</u>**

* **Multi-dimensional Array Operations:** NumPy's primary data structure is the ndarray (n-dimensional array), which allows us to work with arrays of data efficiently. These arrays can have any number of dimensions and are used for tasks like representing data, images, and more.

* **Mathematical and Statistical Operations:** NumPy provides a rich set of mathematical and statistical functions, making it suitable for tasks involving linear algebra, calculus, statistics, and more. We can perform operations like addition, subtraction, multiplication, and division on arrays, as well as advanced operations like matrix multiplication, eigenvalue decomposition, and singular value decomposition.

* **Data Manipulation and Analysis:** NumPy is often used in conjunction with libraries like pandas for data manipulation and analysis. It allows us to load, transform, and manipulate data efficiently, making it a foundational tool for data scientists and analysts.

* **Machine Learning and Data Science:** NumPy serves as a fundamental building block for many machine learning libraries and frameworks, including scikit-learn and TensorFlow. It's used for creating and manipulating data arrays that are fed into machine learning algorithms.

* **Plotting and Data Visualization:** While NumPy itself is not designed for data visualization, it is often used in combination with libraries like Matplotlib and Seaborn to create plots, charts, and visualizations from numerical data.

* **Random Number Generation:** NumPy includes a random number generation module that is useful for tasks like simulations and statistical analysis.

Overall, NumPy is a fundamental tool in the Python ecosystem, and its versatility and efficiency make it indispensable for a wide range of applications, particularly in scientific and numerical computing. NumPy is widely used in data science, machine learning, scientific research, and many other fields where numerical and mathematical operations on large datasets are required.

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Python lists are heterogenous:</code>

* We have learnt about python lists. Lets talk about a very curious aspect of python lists. 
<u>We have seen that python lists can be heterogenous</u>, which means it can store various datatypes as its elements at the same  time.

* But heterogeneity actually creates a problem. Now, in the example below, can we say that int "1" and the string that we have 
at the end will require different space in memory? <u>They will require different amount of memory to be stored in the RAM.</u> 

* Now because they are not same amount of data, they require different amounts of memory for their storage, the 
**storage actually cannot be together. They cannot be stored in boxes in continuous manner in RAM.**

* Boxes in memory have same size-- for example, each box can store 4 bytes of data. So, if data is equal to or small in size 
than 4 bytes, we can keep on storing data in contiguous or continuous manner in boxes.

* **Because python is a dynamic programming language which supports heterogeneity, which means when we create lists, we dont tell python what type of data we are going to store in it, means data can be variable in size and HENCE we dont or cant predict the size of data in python lists.** 

* Think of RAM as a hugh blob of memory. And now somewhere in RAM, "1" will be stored somewhere, "4.5" will be stored
somewhere completely else, "string" will be completely at a different place, same goes with boolean and large int.

* **What happens internally is, when we create a python list, python stores the memory addresses of the locations where the list elements are stored.**

* Lets suppose we are makng tea and we go to a friend's house and make tea. Now in case 1, all the ingridients to make tea are very well organised and stored in one drawer next to each other. But in case 2, all of these ingridients are present in a list where you have been given the locations of those ingridients, where you will find them. But you have to go that address, fetch that ingridient and use it and repeat the process.

* In which of the two cases, will we be able to make tea faster? Obviosly 1st case will be faster.

* **So, whenever we have heterogeneity, it makes something slow. Its like a superpower but it comes at a cost, that is it makes lists bulky. Slow because they allow us for dynamic input of type of elements and customization.**

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Numpy only handles homogenous data:</code> 

* **Whenever we will be working with numpy, we will always be working with homogenous data, which means numpy lists will only contain ints or it will only contain floats  or it will only contain strings. So, thats why numpy lists are called numpy arrays.**

* These numpy arrays are similar to arrays in other programming languages like c++, where arrays are having elements of the 
same data type. 

* **Numpy arrays only store homogeneous data. Homogeneous data will be consistent in size, if its consistent in size, it can be stored in contiguous or continuous memory locations. Numpy arrays could actually be faster than python lists. WE WILL PROVE THIS.**

* We have heard that Java, C, C++ are fast programming languages than python. Why is python slow? 
Because, we have discussed this in the first lecure of python, that **PYTHON IS BUILT AS AN ABSTRACTION ON TOP OF C. Python ultimately gets converted into C code, which then gets converted into machine code. "C is where the python compiler sits."**

* Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

* If we run python in cmd prompt, you will see Clang 13.0.0. and that tells you that python interpretor is built in C.
**So, what happens is that python code gets converted into C code, which then gets complied into machine code.
So, since there is an added step on top of C program, ultimately by nature its bound to get slow.**

* **But numpy, even though it works with python, internally directly uses C, so numpy is not an abstraction on top of python.
Numpy is also an abstraction on top of C, but it utilizes a lot of properties of C, which python does not. So, although python introduced heterogeneity, numpy doesnt introduce it. Numpy is homogenous. Numpy uses a lot of features directly from C and that is why numpy is faster than a lot of core python concepts. Since, numpy is directly compatible with C and C is a homogenous language, numpy arrays are faster than python lists.**

* Numpy and python work in conjunction with each other to get their code converted to C and then to machine language.
Numpy's compatibility with is actually better than python. At the same time all of the python concepts like indexing etc will also work with numpy.

* **As a data scientist who has to work with millions and millions of data, numpy becomes very obvious choice. And, numpy
is omnipresent in all DA/DS roles without fail its gonna come.**

* So, numpy array is built on top of C and is more compatible with C and also takes a lot of features of both C and python, but since its homogenous, its lot faster than python lists. Numpy library is built on top of C not on python.

<hr style="border: 1px solid gray;">

**Here "a" is a heterogenous python list**

In [1]:
a = [1, 4.5, "string", True, 7890234567874345678765, "this is a massive string with a tonne of characters"]

a

[1,
 4.5,
 'string',
 True,
 7890234567874345678765,
 'this is a massive string with a tonne of characters']

**Importing a module**

In [2]:
import math as m  

**Now all the module's methods are available to use with the help of the alias and dot operator.**

In [3]:
m.log(10)  

2.302585092994046

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Using NumPy:</code>

**Once we've installed NumPy, we can import it as a library**

In [4]:
import numpy as np

**Lets create a normal python list a**

In [5]:
a = [1, 2, 3, 4, 5]

**We are creating a python list "res", using list comprehension to create squares of elements of a**

In [6]:
res = [i ** 2 for i in a]  

res

[1, 4, 9, 16, 25]

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Creating NumPy Arrays:</code>

**There are two general purpose or common ways to create a numpy array:**

### <code style="background:yellow;color:black">1. array() function:</code>

* **In NumPy, the <code style="background:yellow;color:black">numpy.array() function</code> is used to create a numpy array.** 
* **<code style="background:yellow;color:black">It can convert a python list, tuple, or any array-like object into a NumPy array.</code>** 
* **The syntax of numpy.array() is straightforward: <code style="background:yellow;color:black">numpy.array(object, dtype = None).</code>** Here "object" is the input data structure, like a list, tuple, or another array. "dtype" is the desired data type of the array. If not specified, NumPy will infer the data type.
* We can create a numpy array using this method which is defined for array object in numpy. We pass a python list or nested lists in array() method as parameters to create nD numpy array.
* **<code style="background:yellow;color:black">We can also create a nD array by directly converting a python list or nested list.</code> Following is an example of creating a numpy array "b" from a python list.**
* In following code cell, we can see type of "b", which is a n-dimensional numpy array. Here, "b" is 1D array. Whereas in next code cell we can see that "a" is a python list.

In [44]:
a = [1, 2, 3, 4, 5]

b = np.array(a)

b

array([1, 2, 3, 4, 5])

In [8]:
type(b)

numpy.ndarray

In [9]:
type(a)

list

### <code style="background:yellow;color:black">2. arange() function:</code>

* **In NumPy, the <code style="background:yellow;color:black">numpy.arange() function</code> is used to create a 1D array with regularly spaced values within a specified range.** 
* **It is similar to the built-in range() function in Python but returns a NumPy array.**
* **<code style="background:yellow;color:black">Format of arange() is: np.arange(start, end, step_size).</code> It works exactly like range(), default step size is 1 same as range(), ending value isnt included just like range().**
* range() in python generates a sequence; we can have a start point, end point and a step size. Similarly arange() in numpy can also have starting point, end point and step size. Starting point is included, ending point isnt included just like range().
* There is one very important thing about this that its spelled as arange() with a single "r" not double "rr". Many people make this mistake, so we have be careful.
* **One added functionality we get in arange(), but will not work in case of lists or python range() function is that it can also work with floating point step sizes or jump values.** This is one added advantage that we get on top of python range() function.


**<code style="background:yellow;color:black">np.arange() and np.array(range())</code> are two ways to create 1D Numpy arrays with regularly spaced values, but they differ in terms of usage and flexibility.**

* **np.arange()**: np.arange() is a function provided by numpy to create a 1D array of evenly spaced values within a specified range. We specify the start, stop, and step size as arguments. For example: np.arange(start, stop, step). It returns an array with values from start to (but not including) stop, incrementing by step.

* **np.array(range())**: In this approach, we first create a python range object using the built-in range() method and then convert it to a numpy array using np.array(). We typically specify the start, stop, and step size using range() and then convert it into an array.

**In practice, np.arange() is more convenient and commonly used because it directly generates a numpy array with the specified values, whereas np.array(range()) involves an extra step of creating a python range object and then converting it into a numpy array. However, both methods ultimately achieve the same result in terms of creating 1D arrays with evenly spaced values.**

* In the code cell example below, we have created a 1D numpy array "a1" using arange() function.
* In next code cell, we have provided different step size. Note that ending element i.e "5" isnt included.
* In the next code cell example below, step size or jump is of "0.5". 
* **One imp thing to note here is that since numpy arrays are homogenous, it cant have int and float together, so in final result array all integers got automatically converted to floating point values to maintain homogeneity.**

In [35]:
a1 = np.arange(1, 5)  

a1

array([1, 2, 3, 4])

In [36]:
a2 = np.arange(1, 5, 2)

a2

array([1, 3])

In [37]:
a3 = np.arange(1, 5, 0.5)

a3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

<hr style="border: 1px solid gray;">

## <code style="background:yellow;color:black">ndim attribute:</code>

* **The <code style="background:yellow;color:black">ndim attribute</code> in NumPy is used to determine the number of dimensions or axes in a NumPy array. It stands for "number of dimensions."** 
* This attribute is particularly useful when we want to understand the dimensionality of an array, which is crucial for many operations and manipulations.
* The .ndim attribute provides a simple and convenient way to check the dimensionality of an array, which is useful when we want to ensure that we are working with data of the correct shape or when we need to perform operations specific to the number of dimensions in your array.

## <code style="background:yellow;color:black">shape attribute:</code>

* **The <code style="background:yellow;color:black">shape attribute</code> in NumPy is not actually a method; it's an attribute of a NumPy array. It provides information about the dimensions of the array.** 
* Specifically, it returns a tuple that represents the size of each dimension in the array.
* For a 1-dimensional array, the shape attribute will be a tuple with a single element indicating the number of elements along that dimension. 
* For multi-dimensional arrays, the shape attribute will be a tuple with multiple elements, each element corresponding to the size of a particular dimension.

**In the code cells below, we are creating two numpy arrays "c" and "d" using array() method and checking its dimensions and shape. "c" is a 2D array and "d" is a 1D array.**

In [48]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
c.ndim

2

In [50]:
c.shape

(4, 3)

In [51]:
d = np.array(range(10000))

In [52]:
d.ndim  

1

In [53]:
d.shape

(10000,)

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Numpy arrays support element wise operations:</code>

In [10]:
b

array([1, 2, 3, 4, 5])

**This operation of element wise operation wont work with python lists**

In [11]:
a ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

**Same operation of squares of elements but using numpy array**

In [12]:
b ** 2

array([ 1,  4,  9, 16, 25])

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">New function to check execution time of a particular operation:</code>

**The <code style="background:yellow;color:black">%timeit function</code> is a built-in magic command in IPython, Jupyter, and some other interactive computing environments. It is used to measure the execution time of a single line of code or a code block. When used, %timeit runs the specified code multiple times and provides information about the average execution time, standard deviation, and other statistics. This is useful for quickly assessing the performance of different code snippets.**

* **We are checking through this function, how much computation time it takes in case of a python list.**
* **Python list's processing times in case of cubes, are in milli seconds, as can be seen in below code cell.**
* **We are checking through this function, how much computation time it takes in case of a numpy array called l.**
* **Hence proved that <code style="background:yellow;color:black">numpy arrays are 1000 times faster than python lists</code> because when we compare numpy array's processing times in case of cubes, they are in micro seconds whereas python list's processing times are in milliseconds.**

In [13]:
%timeit [i ** 2 for i in a]

734 ns ± 36.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [14]:
%timeit [i ** 3 for i in range(100000)]

17.4 ms ± 651 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
l = np.array(range(100000))

%timeit l ** 3

230 µs ± 908 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Why is numpy so fast?</code>

Numpy is often significantly faster than pure python when it comes to numerical and scientific computing tasks. This is because numpy is designed for efficient array operations and mathematical computations, and it's implemented in low-level languages like C, which can perform operations much faster than python, which is an interpreted, high-level language.

- **Homogeneous datatype-** Homogeneity allows NumPy to use contiguous blocks of memory and perform operations more efficiently.
- **Parallelism-** Numpy divides tasks in parallel processes, meaning numpy can take advantage of multi-core processors and parallelism, which speeds up computations for large datasets. 
- **Optimized C Code-** Numpy functions are directly implemented in C. Many of the core functions in NumPy are implemented in C, which is a low-level language that can execute code much faster than Python. This means that many NumPy operations are faster than their equivalent pure Python implementations.
- **Vectorization-** Numpy supports vectorized operations, which means it can operate on entire arrays without the need for explicit Python loops. This allows for highly optimized, low-level operations on data, leading to improved performance.

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Indexing and Slicing of 1D array:</code>

**There are two types of indexing in numpy.**

### <code style="background:yellow;color:black">1. Basic Indexing:</code>

* **All sorts of indexing - positive, negetive works on numpy arrays, similar to python lists.**
* Indexing in NumPy starts at 0.
* Negative indices represent counting from the end (e.g., -1 refers to the last element).
* Slicing in NumPy works similarly to Python lists.

In [54]:
a = np.arange(1, 5, 0.5)

a

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [55]:
a[0]

1.0

In [56]:
a[-1]

4.5

In [57]:
a[2:5]

array([2. , 2.5, 3. ])

### <code style="background:yellow;color:black">2. Fancy Indexing:</code>

* **<code style="background:yellow;color:black">Fancy indexing, often referred to as "masking" in NumPy,</code> is a technique that involves selecting elements from an array based on a set of Boolean conditions (masks) or a list of indices.**
* Fancy Indexing that is unique to numpy.
* It allows us to create new arrays or extract specific elements from an existing array by applying conditions or specifying positions. 
* Fancy indexing is a powerful feature in NumPy that provides flexibility in data selection and manipulation.

In [58]:
m1 = np.array(range(1, 11))

m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**What is the output of this code below? It will return another numpy array which will contain element wise responses. Basically it returns element wise result as a numpy array. Numpy supports element wise operation we know that.**

In [59]:
m1 < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

We will learn three different concepts, and we will combine all to create something very powerful.

* **First concept:** is that element wise operations are possible, which we have seen above.

* **Second concept:** Usually in python, when we have a list like this: a = [1,2,3,4,5] , we can't get different indexes's elements like this: a[1,2,4]. It will throw an error, its not possible in python; selective picking of indexes at the same time. **But selective indexing is possible in numpy arrays, as shown below.**

* **Third concept:** Combine the above two types and make a special type of indexing called fancy indexing. Such as: m1[m1 % 2 == 0] -> output -> This will give all the even elements - array([ 2, 4, 6, 8, 10]). What happens in details working is explained below.

**Below we are trying to fetch elements at multiple indexes at the same time, which is not possible in python lists. But it is possible in numpy arrays.**

In [60]:
a = [1,2,3,4,5]

a[1,2,4] 

TypeError: list indices must be integers or slices, not tuple

In [61]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
m1[[1,5,3,4]]  

array([2, 6, 4, 5])

In [63]:
m1 % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [64]:
m1[m1 % 2 == 0]

array([ 2,  4,  6,  8, 10])

### BREAKDOWN of above code:

- First it will generate result of this: m1 % 2 == 0 -> output of which is an array --> [False, True, False, True, False, True, False, True, False, True]

- And then it will superimpose this on top of this array - [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]. And basically, put them together. 

- It will work like this: If the corresponding value to "1" is "false", then it will not keep it and vice versa. And hence we get the final result.

So, this is sort of indexing by using filters or its like a filtering of data because we are filtering data on the basis 
of a condition. Only values that correspond to "true" are filtered.

<hr style="border: 1px solid gray;">

**<code style="background:yellow;color:black">Almost everything in python is an object</code>**

* **In Python, almost everything is an object. Python is designed to be an object-oriented programming language, and this design choice is reflected in its syntax and semantics.** 
* In Python, objects are instances of classes, and everything in Python, including integers, strings, functions, and even modules, is an object.
* In Python, everything being an object means that variables are references to objects, and objects have a type and can be manipulated accordingly. 
* This object-oriented paradigm is a fundamental aspect of Python's flexibility and expressiveness. It enables features like inheritance, polymorphism, encapsulation, and more.

**<code style="background:yellow;color:black">In a NumPy array, all subarrays (rows) should have the same length</code>**

* **NumPy arrays are designed to represent multi-dimensional arrays where each dimension (or axis) must have consistent lengths.**
* **In terminology, 1D numpy array is called a VECTOR, 2D numpy array is called a MATRIX and 3D numpy array is called 3D numpy array and so on.**
* **So, we dont create a 2D numpy array, we create 2D numpy matrix.**
* When we run the following code, error says it has an inhomogenous shape, which means that when we are working with numpy arrays, we only work with numpy matrices, and we dont work with a data which is not a matrix.

**<code style="background:yellow;color:black">Also note that visualization of 3D arrays is in notes.</code> Refer that.**

In [65]:
np.array([[1],[2,3],[4,5,6],[7,8,9,10]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Typecasting:</code>

* **<code style="background:yellow;color:black">Typecasting</code> in NumPy refers to the process of converting the data type of an array to another data type.** 
* NumPy provides several functions for typecasting, allowing us to convert arrays to different data types according to our needs.
* **When typecasting happens automaticaly, we call this <code style="background:yellow;color:black">INTRINSIC TYPECASTING,</code> but when typecasting happens manually based on user preference, we call this <code style="background:yellow;color:black">EXTRINSIC TYPECASTING.</code>**

**In this example below, if we have a list of int and float, <code style="background:yellow;color:black">numpy will automatically convert them all into floating point values</code> in order for numpy to maintain homogeneity.**

**But what if, we have something like this in the next example code below? We have a list of string and integers. Now <code style="background:yellow;color:black">numpy converts them all to strings.</code> Everything is convertible to strings, even numbers can be strings. Homogeneity is still maintained. And it also tells us the datatype in the rightmost area of the output.** U11 is basically a unicode representation, its a mapping similar to ASCII. It basically tells us that these are strings.

In [66]:
a = [1, 2, 3, 4, 5.6] # List of int and float

a = np.array(a)

a

array([1. , 2. , 3. , 4. , 5.6])

In [67]:
b = np.array(["bipin kalra", 1, 2, 3, 4, 5]) # List of int and string

b

array(['bipin kalra', '1', '2', '3', '4', '5'], dtype='<U11')

* Like we saw above, all the integer values got converted automatically to floating point values in order for numpy to maintain homogeneity; so if we have a list of int and float, numpy will automatically convert them all into floating point values.

* But what if we dont want it to do automatically, that is, we dont want numpy to convert ints to floats forcibly or implicitly or automatically. For eg, if we provide an array like this in example: c = np.array([1,2,3,4.5]), we dont want the default output - array([1. , 2. , 3. , 4.5]).

**Here are some commonly used Extrinsic NumPy typecasting functions:**

* **<code style="background:yellow;color:black">astype() Method:</code>** The astype() method is used to cast an array to a specified data type. It returns a new array with the specified data type.

* **<code style="background:yellow;color:black">numpy.int64(), numpy.float64(), etc.:</code>** NumPy provides specific functions for creating arrays with a particular data type.

* **<code style="background:yellow;color:black">numpy.asarray():</code>** The asarray() function is similar to astype() but returns a view of the input array instead of creating a new array.

Lets see these examples below of extrinsic typecasting-

In [69]:
arr = np.array([1, 2, 3, 4, 5])

arr_float = arr.astype(float) # Convert to float using astype() method

arr_float

array([1., 2., 3., 4., 5.])

In [71]:
arr1 = np.array([1, 2, 3, 4, 5])


arr_float1 = np.float64(arr1) # Convert to float using np.float64 method

arr_float1

array([1., 2., 3., 4., 5.])

In [72]:
arr2 = [1, 2, 3, 4, 5]

arr_float2 = np.asarray(arr, dtype = float) # Convert to float using asarray() method

arr_float2

array([1., 2., 3., 4., 5.])

In [73]:
d = np.array([1, 2, 3, 4], dtype = "float")

d

array([1., 2., 3., 4.])

* If we provide a heterogenous list to a numpy array, all the different datatypes can be converted to one common consistent datatype, and numpy will do that. It will automatically do that type conversion.

* But if we want to do it ourself- lets suppose we are providing a bunch of ints and we want to convert them to floats manually, we can also specify the datatype that this numpy array is going to have at the time of creation of that array, by specifying dtype = "float" or for string dtype = "U21".

* **A problem or shortcoming of this is that when we provide the user the capability to change, user can do something like this in the example below. Floats can be converted to strings. <code style="background:yellow;color:black">CAN STRINGS BE CONVERTED TO FLOATS? NO THATS NO POSSIBLE. THATS WHERE ERROR OCCURS.</code> Its nonsensical to a certain degree. And thats why numpy does not allow that.**

* While we have a lot of manual conversion capability avaliable, some of it cant be used.

In [34]:
e = np.array(["This", "is", "absurd!"], dtype = "float")

ValueError: could not convert string to float: 'This'

<hr style="border: 1px solid gray;">

1. Wherever possible, in numpy lectures, we will discuss very very small case studies or discussions, where we will utilize 
whatever we have learnt in the current lecture. In some lectures, we will have it. So, today's case study is about NPS.

2. <code style="background:yellow;color:black">**NPS is Net Promoter Score.</code> Many companies are using NPS as a very important metric to understand how customers are perceiving our product, what is their experience with our product.**

3. In NPS, what we usually get is a rating from 0 to 10. So how likely are you to recommend this product or company to your 
friends or colleagues. You are asked to rate on a basis of 0 to 10. 

4. Anybody in a range of 0 to 6 is called a **detractor**, that is, this is somebody who might not recommend our product to 
somebody else. Anybody in range of 7,8 is called **neutral**, that is, does not like does not hate it but may not recommend.
Anybody in range of 9,10 is basically a **promoter**, that is, somebody who is happy with the product and will recommend 
the product to other people and these are the kind of people we need.

5. How we calculate NPS? We calculate NPS by saying **NPS = % promoters - % detrators**. So, fo eg, in 1000 people, how much percentage of people are promoters and how much percentage of people are detractors.

6. **Usually in companies, getting a NPS of > 70 is considered to be amazing. And interestingly NPS IS USED BY MAJORITY OF 
FORTUNE 500 COMPANIES. Scaler also uses it. So, if you go in a company to work as a DA, you might work on NPS.**

# <code style="background:yellow;color:black">NPS CASE STUDY:</code>

**The "gdown" tool is a command-line utility and Python library for downloading files from Google Drive using their unique file IDs. It's a convenient way to download files from Google Drive without requiring a Google Drive share link. You can use "gdown" to fetch files directly by specifying the file's ID in the URL.**

We need to install the "gdown" library if we haven't already by using pip installer.

In [2]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: C:\Users\Lenovo\OneDrive\Desktop\Scalar\Module 5- Python Libraries\My Practice\Class Practice\survey.txt

  0%|          | 0.00/2.55k [00:00<?, ?B/s]
100%|##########| 2.55k/2.55k [00:00<?, ?B/s]


In [45]:
score = np.loadtxt("survey.txt", dtype = "int")

In [46]:
type(score)

numpy.ndarray

In [47]:
score.shape

(1167,)

In [48]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [49]:
len(score[score < 7])

332

In [50]:
len(score)

1167

In [51]:
len(score[score > 8])

609

In [52]:
detractor_percent = len(score[score < 7]) / len(score) * 100

In [53]:
promoter_percent = len(score[score > 8]) / len(score) * 100 

In [56]:
NPS = round((promoter_percent - detractor_percent),2)

In [57]:
print(f"NPS is {NPS}")

NPS is 23.74
