# <code style="background:yellow;color:black">Summary:</code>

1. Copies of data
2. Shallow and how to create it using view() function
3. Deep copy and how to create it using copy() function
4. When numpy creates which copy and overview of memory management of numpy
5. shares_memory() function to identify whether it is deep or shallow copy
6. Splitting data
7. Stacking data
8. Concatenate data
9. flatten() method

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Copies of Data:</code>

* **As a data scientist, we will be working with millions of rows of data. So, numpy on top of being very fast, also has to be memory efficient, because if its not memory efficient our computer or system might run out of memory, and we wont be able to work with that dataset.**

* So ultimately, storage space is a baseline requirement for numpy to be able to work with data because memory is continuosly either occupied or freed with each line of the program or with execution every of task. **<code style="background:yellow;color:black">Therefore, numpy internally has done a lot of optimizations so that it can optimize on storage / memory space.</code>**<br><br>

* Lets suppose there is a bunch of data in excel. This data is for multiple cars. The cars data has 3 columns called Car model, Manufacturer and Date of launch. There are some entries i.e. rows in the data. **REFER NOTES TO SEE DATA.**

* Lets suppose we only have to show data for tata, what would we do? Will we copy all the tata entries to another excel sheet or simply apply a filter to filter out tata entries? Obviously we will apply a filter on the manufacturer, which means that filter will show you us tata data only, but the rest of the data will still be there. 

* **It means internally all the data is present but only filtered data is visible to us as a user. OR WE CAN ALSO SAY THAT BOTH THE DATAFRAMES OR BOTH THESE SOURCES OF DATA IS THE SAME, WE ARE JUST LOOKING AT DIFFERENT VIEWS OF THE DATA.**

* Internally there is one single dataset, but we are just looking at different views of that same data. In one view, we are looking at all the manufacturers and in another view we are only looking at tata data.<br><br>

* **Now, when it comes to numpy, we are doing as lot of operations on data. Some of those operations are permananet and some of those opearations are operations which can be either reversible or changed or are only done to present the data in a different format. These operations do not change the structure or the value of the data but they just present the data differently.** 

* **So NUMPY AUTOMATICALLY HAS DIVIDED ALL ITS OPERATIONS INTO THESE TWO CATEGORIES.**

    * **<code style="background:yellow;color:black">Category 1</code>** are those opeartions which are permanent or important operations on data. 

    * **<code style="background:yellow;color:black">Category 2</code>** are operations which are just on the look of data or view of the data. 

**AND IN BOTH THESE CASES NUMPY HANDLES MEMORY DIFFERENTLY. We will see this in action.** 

**In NumPy (and in Python in general), <code style="background:yellow;color:black">the concepts of shallow copy and deep copy</code> refer to how the copying of objects is handled, especially when dealing with nested or compound objects like arrays or lists.**

### <code style="background:yellow;color:black">Shallow Copy of Data:</code> 

* **<code style="background:yellow;color:black">A shallow copy</code> creates a new object, but does not create copies of the nested objects within the original object. Instead, it copies references to the nested objects. As a result, changes made to the nested objects within the copied object will be reflected in the original object, and vice versa.**

* **<code style="background:yellow;color:black">A shallow copy</code> of an array means a new array that is a copy of the original array's data and shape but shares the same memory addresses as the original array. In other words, both of these arrays are sharing the same memory addresses. Changes made to the data within a shallow copy will also affect the original array, and vice versa.**

* If we look at a and b in the example code cell below, both a and b are similar in data but different in the view of that data, which means they look and feel different and are presented differently but the data within them is the same. **So in such cases, what numpy does is it creates a <code style="background:yellow;color:black">SHALLOW COPY of data</code>.** 

* To prove it, below we are changing a[0] to 100, obviously "a" gets modified and now has 100 as its 1st element, **BUT B ALSO HAS THE SAME 100. IT ALSO CHANGED ITS 1ST ELEMENT.**  

* **<code style="background:yellow;color:black">Numpy creates a shallow copy WHEN RESHAPING.</code>**

* So, what numpy has done internally, is that all the elements are shared between both the array "a" and "b", so that when we modify one of the elements of "a" array, since the memory address was common and since the elements were shared between the two arrays, the "b" array also got affected. 
* Here, numpy did not duplicate the data two times, what it did is actually created two pointers or references to that data, one reference was "a" and one reference was "b".
* "b" and "a" were both looking at the data in different ways, but ultimately the data was exactly the same.

### <code style="background:yellow;color:black">shares_memory() function:</code>

* **This is used to determine whether two arrays share the same memory block or addresses. This function returns a boolean value, indicating whether the two arrays share memory or not.**
* **The np.shares_memory() function takes two NumPy arrays as arguments and checks if they have overlapping memory or if they are views of the same data. If they share memory, the function returns True; otherwise, it returns False.**
* Through this function in next code cell below, we are checking and finding that "a" and "b" share memory and either one is the shallow copy of the other.

In [1]:
import numpy as np

In [2]:
a = np.arange(4)

a

array([0, 1, 2, 3])

In [3]:
b = a.reshape(2, 2)

b

array([[0, 1],
       [2, 3]])

In [4]:
a[0] = 100

a

array([100,   1,   2,   3])

In [5]:
b

array([[100,   1],
       [  2,   3]])

**This means that either "b" is a shallow copy of "a" or "a" is a shallow copy of "b".**

In [6]:
np.shares_memory(a, b)

True

### <code style="background:yellow;color:black">Deep Copy of Data:</code> 

* **A deep copy of an array is a completely independent copy of the original array, which means it has its own memory address. In other words, both of these arrays have different memory addresses and are not sharing them.**
* **Changes made to a deep copy do not affect the original array, and vice versa.**

**Now, when is numpy creating deep copy or how it works?**

* Below we created a 1D np array "a". 
* We also created another array "c" and make it "a + 2". 
* **<code style="background:yellow;color:black">Numpy considers addition, subtraction, multiplication these kind of operations to be more permanent in nature, because all the individual elements are updated or changed i.e. data is changed.</code>** 
* So if we create "c" from "a", "c" has different data than "a". 
* Now if we check by "shares_memory() function", we will see that "a" and "c" do not share memory. 
* **We can further prove this by changing first element of "c" to 100, and "c" array gets updated as we can see below. <code style="background:yellow;color:black">BUT ARRAY "A" IS NOT CHANGED AT ALL, ITS FIRST ELEMENT IS AS IT IS, IT HASNT CHANGED.</code>**
* Why because "c" was stored in an entirely different memory location and "a" has been stored in an entirely different location and they do not share their memory addresses, and python can clear identify where "a" and "c" are located in memory locations.

**"C" IS A DEEP COPY OF "A". Why do we say that c is a copy of a although c is altogether a different array in terms of data? - BECAUSE C COPIED THE DATA FROM A AND THEN MODIFIED THE DATA BY ADDING 2 TO IT. IN OTHER WORDS, C TOOK A DEEP COPY OF A AND THEN ADDED 2 TO IT.**

**<code style="background:yellow;color:black">Numpy does all this decisions on whether to share memory or not internally on its own, but numpy has given us shares_memory() function to check the memory sharing between two np arrays.</code>** 

* **Actually there are so many cases that in some memory is shared and in some memory isnt shared, and so remembering all those cases becomes difficult, so we have this function to check the same.**

* **We will learn a sure shot way to understand where will numpy create a shallow copy and where will it create a deep copy.**

In [7]:
a = np.arange(4)

In [8]:
c = a + 2

In [9]:
a

array([0, 1, 2, 3])

In [10]:
c

array([2, 3, 4, 5])

In [11]:
np.shares_memory(a, c)

False

In [12]:
c[0] = 100

c

array([100,   3,   4,   5])

In [13]:
a

array([0, 1, 2, 3])

**Now here in this case below, even though "a" and "b" both hold the same value or data, numpy does not share memory addresses of these arrays, and it created a deep copy because it figured that a multiplication operation requires a deep copy.**  

In [14]:
a = np.array([0, 0, 0, 0])

a

array([0, 0, 0, 0])

In [15]:
b = a * 2

In [16]:
a, b

(array([0, 0, 0, 0]), array([0, 0, 0, 0]))

In [17]:
np.shares_memory(a, b)

False

* Here, in this case below, "a" and "b" have different data, they are not the same exact lists. 
* But in this case, numpy allows sharing memory addresses of these two arrays. 
* Lets look at it like the excel example previously. 
* We can see "b" as a filter that has been applied on "a" or that "b" is a subset of "a". 
* So all the data in "b" is still present inside of "a", which means if we modify the data in "a", data in "b" will be modified too because "b" is a subset of "a". 
* We change the 1st element in "b" to 1000 and we check "a" is also updated. 
* **REFER NOTES VERY WELL EXPLAINED WITH VISUALIZATION.**
* So, here we see that 2 different np arrays dont necessarily share data but they can share memory addresses because one can be a subset of the other.
<br><br>
* Deep copy of one array wrt another array means both the arrays are stored at different memory locations in memory. 
* **<code style="background:yellow;color:black">So, the cases are very varied apart. There can be cases where the data or values is different but a shallow copy is created and conversely there can be cases where the values can be same but the copy created is a deep copy.</code>** 
* **<code style="background:yellow;color:black">NUMPY DECIDES INTERNALLY AUTOMATICALLY WHICH COPY TO CREATE OR WHICH FORMAT OR RULE TO FOLLOW, which is the reason numpy has given us this shares_memory() function.</code>** 
* We can try or explore further and see which cases create a deep copy and which creates a shallow one. See what copies different kind of operations like arithmetic, logical, masking, indexing, slicing etc create.

In [18]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b = a[::2]

b

array([0, 2, 4, 6, 8])

In [20]:
np.shares_memory(a, b)

True

In [21]:
b[0] = 1000

a

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [22]:
0 % 1

0

**This is another example to see if a shallow or deep copy is created, and we see a deep copy is created.**

In [23]:
a = np.arange(6)

b = a[a % 1 == 0]

b[0] = 10

In [24]:
a

array([0, 1, 2, 3, 4, 5])

In [25]:
b

array([10,  1,  2,  3,  4,  5])

In [26]:
np.shares_memory(a, b)

False

So, up and untill this point of time in disussion, we can to understand the following:

* **<code style="background:yellow;color:black">Shallow Copy is created in these cases - Reshaping, Slicing....(and the list goes on which we can explore)</code>**
* **<code style="background:yellow;color:black">Deep Copy is created in these cases - Arithmetic Operations, Masking....(and the list goes on which we can explore)</code>**
<br><br><br>
* Now, we know numpy creates shallow and deep copies of arrays and it handles memory management on its own. 
* **<code style="background:yellow;color:black">BUT WHAT IF WE WANT A SHALLOW OR DEEP COPY EXPLICITLY WITHOUT DOING ANY OPERATION ON THAT ARRAY, WITHOUT NUMPY DOING EVERYTHING ON ITS OWN, MEANS NUMPY DECIDING WHETHER IT WILL BE SHALLOW OR DEEP ON ITS OWN?</code>** 

### <code style="background:yellow;color:black">view() method:</code> 

* **This <code style="background:yellow;color:black">view() method</code> creates a shallow copy of the array. It is used to create a new array object that shares the same data with the original array.**
* Changes to the data in the view will affect the original array, and vice versa.

### <code style="background:yellow;color:black">copy() method:</code> 

* **This <code style="background:yellow;color:black">copy() method</code> always creates a deep copy of the array.**
* It is explicitly designed to create an independent copy of the array, and modifications to the copied array do not affect the original.

In the following examples we can see these methods in action.

In [36]:
a = np.arange(10)

**Creates a shallow copy of "a".**

In [37]:
a_shallow_copy = a.view() 

In [38]:
np.shares_memory(a, a_shallow_copy)

True

In [39]:
a, a_shallow_copy

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [41]:
a_shallow_copy[0] = 100

a, a_shallow_copy

(array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9]),
 array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9]))

In [42]:
a = np.arange(10)

**Creates a deep copy of "a".**

In [43]:
a_deep_copy = a.copy() 

In [44]:
np.shares_memory(a, a_deep_copy)

False

In [45]:
a, a_deep_copy

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [46]:
a_deep_copy[0] = 100

a, a_deep_copy

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9]))

### <code style="background:yellow;color:black">Why we are learning this shallow and deep copies or memory management of numpy at a very higher level?</code>

* We should be aware of it because numpy functions that way or uses it for memory optimization. 
* If we are not aware of this, then we might feel that our data is misbehaving. 
* We might not know why something else is changing while we are expecting something else. 
* So, its very important to know how numpy is handling the memory side of things. 
* **We wont be using this concepts directly for data science, but this is sort of going to get applied unintentionally and we dont have control over it, which is why we should have a great understanding of it.**

We can dive deep between shallow and deep copies, we can refer to these official documetations of numpy:

#### `.copy()` -- Returns copy of the array.

Documentation (`.copy()`): https://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html#numpy.ndarray.copy

Documentation: (`np.copy()`): https://numpy.org/doc/stable/reference/generated/numpy.copy.html

* When we are doing any operations on arrays, then numpy will decide automatically.
* **<code style="background:yellow;color:black">But when we want ourself to create a copy of array, then control is with us, we can decide whether we want a shallow copy or deep copy using .copy() or .view(), otherwise during operations as mentioned earlier numpy automatically decides because numpy handles memory allocations automatically.</code>**
* Lets suppose we got a list that we need to sort. 
* But in our use case, we need to maintain or dont want to destroy the original list, so we will create a copy of it in another list and then sort that copied list. 
* Because lets suppose we need to present the original array and the sorted array both, so if we do an in-place sort on the original list, our unsorted original list is gone which we need to present somewhere. 
* One way of doing this is like the code below -- np.sort(a) doesnt sort the original "a" but creates a copy of "a" in a_sorted list and then sorts it.
* Another way of doing it is to create a deep copy of "a" i.e. array "b". 
* We cant do a shallow copy of "a" because then if we would sort "a" then "b" would also change. So we can see in code below that "b" is sorted but "a" is not sorted.

**<code style="background:yellow;color:black">So, in any case where we have to maintain original data, where we cant loose the structure, order, authenticity of the original data but still we have to do multiple operations -- THERE WE WILL BE CREATING DEEP COPIES, i.e. copies of data which do not modify the original data.</code>** 

* We might do this frequently in data science.
* When we will be exploring data, we will have to do a lot of operations on data and some of these operations will not be successful. 
* Whenever we will have unsuccessful operations, we will have to go back to the original data, but if we loose the original data, how will you do that? 
* **So if we do not create a deep copy of the original data, when we might have to reverse the operation we performed on data it will not be possible. So for these reasons we have to maintain deep copies.** 

In [47]:
a = np.array([10, 15, 25, 5, 20, 0, 30])

In [48]:
a_sorted = np.sort(a)

In [51]:
a, a_sorted

(array([10, 15, 25,  5, 20,  0, 30]), array([ 0,  5, 10, 15, 20, 25, 30]))

In [52]:
b = a.copy()

In [53]:
b.sort()

In [54]:
b

array([ 0,  5, 10, 15, 20, 25, 30])

In [55]:
a

array([10, 15, 25,  5, 20,  0, 30])

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Splitting Data:</code>

* **<code style="background:yellow;color:black">Splitting the data</code> means breaking the data into small pieces.** 
* In NumPy, the term "splitting" typically refers to the process of dividing an array into multiple smaller arrays along a specified axis. 
* NumPy provides several functions for splitting arrays, and the choice of function depends on the desired outcome.

### <code style="background:yellow;color:black">split() function:</code>

* **The <code style="background:yellow;color:black">split() function</code> allows us to split a NumPy array into multiple subarrays along a specified axis.** 
* It divides the original array into smaller, equally-sized parts (if possible) and returns a list of these subarrays. We specify the number of splits and the axis along which the split occurs.
* **split() takes the following arguments:**
    * **ary:** The array we want to split.
    * **indices_or_sections:** It specifies how the array should be divided. It can be an integer, a list of indices, or a sequence of integers.
    * **axis (optional):** The axis along which the array should be split. By default, it's 0, meaning the array is split along its first dimension.
<br><br>
* Splitting the array using split() is somewhat similar and different as well compared to splitting strings. 
* split() splits the array in similar fashion i.e. splitting something big into small small pieces but the way it works and the input it takes is different. 

**Because <code style="background:yellow;color:black">np.split() can split arrays in 2 ways, either it can split in an "n" amount of sections or it can split about a given amount of indexes,</code> both ways are explained below.**

**<u><code style="background:yellow;color:black">Splitting in n sections:</code></u> Format: np.split(array, number_of_sections)**

* If data is not divisible by number of sections, it will throw an error. 
* **SPLIT CAN ONLY AND ONLY WORK IF EVERY SINGLE SECTION WILL GET EQUIVALENT AMOUNT OF DATA. IF THE TOTAL NUMBER OF ELEMENTS IS NOT DIVISIBLE BY THE NUMBER OF SECTIONS WE INTEND TO MAKE, THEN THE SPLIT() FUNCTION WILL NOT WORK.** 
* Following examples shown below illustrate this.

**<u><code style="background:yellow;color:black">Splitting on the basis of exact indexes:</code></u> Format: np.split(array, [list_of_indexes])**

* **Np will create a split right before that index.**
* There is one more way when it comes to splitting np array. And that is by exact cutting points. 
* So lets supoose we got this entire array and we decided exactly where we want to split for example at index number 3 and at index number 5 and at index number 7. In the example below, we are splitting array "b" at indexes 3,5,9.

In [56]:
a = np.arange(9)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
np.split(a, 3) 

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [58]:
b = np.arange(14)

b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [59]:
np.split(b, 3)

ValueError: array split does not result in an equal division

In [60]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [61]:
np.split(b, [3, 5, 9]) 

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13])]

### <code style="background:yellow;color:black">np.array.split() function:</code>

* We have to keep in mind that the total size of the array should be evenly divisible by the number of sections we specify. If not, we'll get a **ValueError** indicating that the split is not possible with equal-sized subarrays. 
* **In that case, we can also use <code style="background:yellow;color:black">np.array_split() function</code> because it allows us to split an array into unequal parts.**

Below is an example of the same.

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split the array into three subarrays, which might have uneven sizes
sub_arrays = np.array_split(arr, 3)

sub_arrays

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

* **If the data is huge in the form of a 2D array, lets suppose we are dividing the data into two equal halves.** 
* So first we will make sure that our data is divisible by 2. 
* **If our data is not divisible by 2, we will take out that last row and store it in a seperate array, and then we will split the data into 2, append the last row back whichever way we want to append.** 
* We dont need to know the exact size of the data because we only need to provide the number of sections, and if we want to verify if our data can be divided into those many sections, we can simply check the length of the data, which it will tell us how many rows of data we have. 
* **Here in below example, we have 9 element 1D array, and we want to split the data into 4 sections- namely "w", "x", "y", "z". So we will take out the last element and store it in "z" array, and then use the spilt() function to split the array in 3 equal parts "w", "x" and "y".**

In [63]:
a = np.arange(10)

In [65]:
z = a[-1]

z

9

In [66]:
# Creating remaining 3 sections by not splitting the entire array a, but splitting from 0 to -1

w, x, y = np.split(a[0:-1], 3)

In [67]:
w, x, y

(array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]))

### <code style="background:yellow;color:black">np.hsplit() function:</code>

**This <code style="background:yellow;color:black">np.hsplit() function</code> splits an array horizontally (hsplit) along its columns or rows, respectively.**
* It is convenient when working with two-dimensional arrays.
* When it comes to 2D array, we can split data horizontally and we can split data vertically. To visualize more, REFER NOTES.
* **This function splits the data on horizontal axis.**
* It works in the exact same way as split() i.e. in "n" number of sections or at specific indexes.
* Here in the code cell below, we are doing splitting by "n" number of sections.
* In the next code cell below that, we are doing splitting by specific indexes.

In [68]:
a = np.arange(36).reshape(6, 6)

a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [69]:
# Here we are splitting by "n" number of sections.

np.hsplit(a, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [70]:
# Here we are doing splitting by specific indexes.

np.hsplit(a, [2,5])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16],
        [20, 21, 22],
        [26, 27, 28],
        [32, 33, 34]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]])]

In [71]:
# Note that there are no elements at 1000th index on horizontal axis, the index is out of range or out of bounds, 
# so it will still split but will return an empty array at the end, and not throw an error.
# REFER NOTES FOR FOR CLARITY AND VIZUALIZATION.

np.hsplit(a, [2,5,1000])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16],
        [20, 21, 22],
        [26, 27, 28],
        [32, 33, 34]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]]),
 array([], shape=(6, 0), dtype=int32)]

### <code style="background:yellow;color:black">np.vsplit() function:</code>

* **This <code style="background:yellow;color:black">np.vsplit() function</code> splits an array vertically (vsplit) along its columns or rows, respectively.**
* It is convenient when working with two-dimensional arrays.
* **This function splits the data on vertical axis.**
* It works in the exact same way as split() i.e. in "n" number of sections or at specific indexes.
* Here in the code cell below, we are doing splitting by "n" number of sections.
* In the next code cell below that, we are doing splitting by specific indexes.

In [72]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [73]:
# Splits the data on vertical axis

np.vsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [74]:
# Here we are doing splitting by specific indexes.

np.vsplit(a, [1, 4])

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Stacking Data:</code>

* **In NumPy, <code style="background:yellow;color:black">stacking refers to the process of combining or concatenating multiple arrays into a single array.</code>** NumPy provides several functions to stack arrays in different ways, such as horizontally, vertically, or depth-wise.
* This is the opposite of splitting data, means joining data together, merging or stacking. So, we can stack data vertically and we can stack data horizontally. REFER NOTES HERE.

### <code style="background:yellow;color:black">vstack() function:</code>

* **In NumPy, the <code style="background:yellow;color:black">np.vstack() function</code> is used to vertically stack or concatenate two or more arrays along their rows. It takes a sequence of arrays as its argument and returns a new array with the input arrays stacked on top of each other.** 

* **The primary argument of np.vstack() is:**
    * **tup:** This is a tuple or sequence of arrays that you want to stack vertically.
    * Note that vstack() function can have list as an argument or tuple as an argument too.
<br><br>
* In the below example, same "data" is stacked on top of one another in total 3 times.
* So, np.vstack((data, data, data)) would work too, note that data is provided as a tuple as argument to vstack().
* **<code style="background:yellow;color:black">Also note that the shapes of all arrays should be same in order for vstack to work.</code>** There is a very legitimate reason for this. 
* Lets suppose we have data of stocks for 2015 to 2022. Now if we are adding data below it, the dimensions of the data have to mactch right. Otherwise the data would not make sense, the header would be something else the value would be something else or there will be a header and the value would be missing. 
* **So, <code style="background:yellow;color:black">when there is data that needs to be stacked or combined VERTICALLY,</code> the data that is getting added should have the exact same number of columns. The number of rows can be different.**
* Note that in the example below "a" is a 1D array with 4 elements and "b" is a 2D array with shape of 4,4 and has 16 elements. * Here, "a" and "b" has different number of rows but same number of columns. So, vstack() works.
* **<code style="background:yellow;color:black">When there is data that needs to be stacked or combined HORIZONTALLY,</code> the data that is getting added should have the exact same number of rows. The number of columns can be different.**
* These all concepts are explained below.

In [10]:
data = np.arange(5)

data

array([0, 1, 2, 3, 4])

In [11]:
np.vstack([data, data, data])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [12]:
# NOTE THAT SHAPES OF ALL ARRAYS ARE SAME SO VSTACK WORKS.

a = np.arange(1, 5)
b = np.arange(2, 6)
c = np.arange(3, 7)

In [13]:
# This is different data stacked on top of one another in total 3 times.

np.vstack([a, b, c])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [14]:
# NOTE THAT SHAPES OF ALL ARRAYS ARE DIFFERENT SO VSTACK DOES NOT WORK.

a = np.arange(1, 5)
b = np.arange(2, 4)
c = np.arange(3, 10)

In [15]:
np.vstack([a, b, c])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

In [16]:
a = np.arange(1, 5)

a

array([1, 2, 3, 4])

In [17]:
b = np.arange(16).reshape(4, 4)

b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
np.vstack([b, a])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 1,  2,  3,  4]])

### <code style="background:yellow;color:black">hstack() function:</code>

* **In NumPy, the <code style="background:yellow;color:black">np.hstack() function</code> is used to horizontally stack or concatenate two or more arrays along their columns. It takes a sequence of arrays as its argument and returns a new array with the input arrays stacked adjacent to each other.** 
* **The primary argument of np.vstack() is:**
    * **tup:** This is a tuple or sequence of arrays that you want to stack vertically.
    * Note that vstack() function can have list as an argument or tuple as an argument too.
* Here in the example below, "a" and "b" have same number of rows but different nnumber of columns. So hstack() works.

In [19]:
a = np.arange(5).reshape(5, 1)

a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [20]:
b = np.arange(15).reshape(5, 3)

b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [86]:
# Here a and b have same number of rows but different nnumber of columns. So hstack() works.

np.hstack([a, b])

array([[ 0,  0,  1,  2],
       [ 1,  3,  4,  5],
       [ 2,  6,  7,  8],
       [ 3,  9, 10, 11],
       [ 4, 12, 13, 14]])

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Concatenate Data:</code>

* **<code style="background:yellow;color:black">Concatenate</code>is one more way of doing stacking only, but it is like a combination function for both hstack and vstack, means it is a combined version of hstack and vstack.**

### <code style="background:yellow;color:black">concatenate() function:</code>

* **In NumPy, the <code style="background:yellow;color:black">np.concatenate() function</code> is a more general-purpose function for concatenating two or more arrays along an existing axis. It allows us to concatenate arrays along any specified axis, not just the second axis (as with np.hstack() or np.vstack()).** 
* **The general syntax is: np.concatenate((array1, array2, ...), axis = 0, out = None)**
    * array1, array2, ...: Sequence of arrays that we want to concatenate.
    * axis: Axis along which the arrays will be joined. Default is 0 (concatenate along the first axis).
    * out: Optional parameter providing a location where the result is stored.
<br><br>

* **For concatenate to work, there is a very very important constraint that both the arrays should have the same number of dimensions.** 
* Here in below example, array "a" is 1D and array "b" is 2D. So, concatenate will not work. So, there is a smart workaround. 
* Simply convert 1D to 2D which is done below after the error. And that is by applying one more set of [] in a to make it a list inside a list i.e. 2D. Axis 0 means we are concatenating vertically. 

**<code style="background:yellow;color:black">When it comes to concatenate there are following rules:</code>**
1. **Number of dimensions must be same**
2. **Axis -** 
    * vstack -> axis = 0
    * hstack -> axis = 1

In [88]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [89]:
a

array([1, 2, 3])

In [90]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
np.concatenate([a, b], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [26]:
a = np.array([[1, 2, 3]])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [27]:
# a and b have same number of columns, so they can be concatenated vertically. Note that axis = 0.

np.concatenate([a, b], axis = 0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [28]:
a = np.arange(4).reshape(2, 2)
b = np.arange(8).reshape(2, 4)

In [29]:
a

array([[0, 1],
       [2, 3]])

In [30]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
# a and b have same number of rows, so they can be concatenated horizontally. Note that axis = 1.

np.concatenate([b, a], axis = 1)

array([[0, 1, 2, 3, 0, 1],
       [4, 5, 6, 7, 2, 3]])

**<code style="background:yellow;color:black">IMPORTANT:</code>**

* We dont have joins like sql in numpy or python. Why would we do sql joins in numpy? We have joins in sql so we dont need them in numpy. Means we do joins in sql and then we dont require joins operation in python. 
* **There is a concept called DATA PIPELINE. Everyone of these tools, like sql, tableau, excel, python, numpy plays a seperate role in this data pipeline. As a data analyst, its not that we will either use sql or we will use tableau or we will use python. WE WILL ACTUALLY USE ALL OF THESE TOOLS.** 
* **SQL WILL BE FOR FETCHING DATA, PYTHON WILL BE FOR WORKING ON DATA.** 
* Within python also there will be two options one is numpy and one is pandas. 
* Numpy is like the brain behind pandas. And, pandas has been built on top of numpy to work beautifully with data. 
* **So everything and anything that we feel is required directly for data, we will find it in pandas and not numpy. SO WE USE BOTH NUMPY AND PANDAS TOGETHER.**

In [32]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

* In above example, "a" and "b" both are nested arrays or 2D arrays. 
* **Now in below code, we are providing axis = None.** 
* Numpy has a special feature via which it will just flatten the entire array. 
* **<code style="background:yellow;color:black">What soes flattening mean? It means REMOVING NESTING. Removing dimensions, converting everything to one single dimension.</code>** 
* Concatenate has this special feature.

### <code style="background:yellow;color:black">flatten() method:</code>

**In NumPy, the <code style="background:yellow;color:black">flatten() method</code> is used to return a copy of the array collapsed into a one-dimensional array. The original array remains unchanged. The flatten() method always returns a flat copy of the original array, even if the original array is already one-dimensional.**

In [33]:
np.concatenate([a, b], axis = None)

array([1, 2, 3, 4, 5, 6])

In [34]:
np.flatten([[[[1, 2, 3]], [2, 3, 4, 5, 5, 6, 6]]])

AttributeError: module 'numpy' has no attribute 'flatten'

In [36]:
a = np.array([[1, 2, 3], [5, 6, 7], [8, 9, 10]])

a

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [37]:
a.flatten()

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])