# <code style="background:yellow;color:black">Summary:</code>

1. Sort() method
2. Argsort() method
3. ones() and zeros() functions
4. eye() function
5. Ufunc sorting
6. Element wise operations
7. Matrix multiplication
8. Vectorization
9. Broadcasting

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Revision of last lecture:</code>

In [1]:
import numpy as np

**Quiz**

arr = np.arange(12) <br>
arr = arr.reshape(-1,4)

What will the shape of array ?

1. (-1, 4)
2. (12,)
3. (3, 4)
4. (1, 12)

In [2]:
arr = np.arange(12)

In [3]:
arr = arr.reshape(-1,4)

In [4]:
arr.shape

(3, 4)

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Sort() Method:</code>

* **In NumPy, <code style="background:yellow;color:black">the sort() method</code> is used to sort the elements of a NumPy array along a specified axis. It can sort the elements in ascending or descending order based on the axis specified.** 

* **A default sort() method implementation looks like this -- np.sort(a, axis = -1, kind = None).**

* **It takes following arguments:**
    * **a:** The input NumPy array to be sorted.
    * **axis:** The axis along which the sorting should be performed. By default, it sorts along the last axis (axis = -1). 
    * **kind:** This specifies the sorting algorithm to use. It can take values like 'quicksort', 'mergesort', or 'heapsort'. The default is None.<br><br>
    
* **Here in the example code cell below, "b" stores the sorted version of "a", and sorting is in increasing order by default.** 
* **Original array "a" will remain unchanged, because a sorted version of "a" is copied in "b" and "a" itself remains as it is. This is called creating a COPY.**

In [5]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [7]:
b = np.sort(a)

In [8]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [10]:
d = a

In [11]:
d

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

* **<code style="background:yellow;color:black">Directly applying sort() function to the original array is called IN-PLACE SORTING.</code>** This does not create and return a sorted copy of the original np array, but it sorts the original np array itself, in this case "d". 

* **<code style="background:yellow;color:black">This is the difference between np.sort(a) and a.sort()</code>,** that when we provide np.sort(a) it will sort and return a copy of array "a", whereas a.sort() will sort the original array "a" itself, no copy will be created.

In [12]:
d.sort()

In [13]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Argsort() Method:</code>

* **The <code style="background:yellow;color:black">argsort method()</code> in NumPy is used to return the indices that would sort an array.** 

* It returns an array of indices that would arrange the elements of the input array in ascending order. 

* This can be very useful when we want to sort one array while maintaining the original order of elements in another array or when you want to apply a custom sorting order.

* **<code style="background:yellow;color:black">sort() returns the sorted array and argsort() returns the indexes of the array if it was sorted.</code>**

* Here in the example code cell below, we get a np array which is telling us the INDEXES of the original array if they were in sorted order. **Refer notes to visualize.**

In [14]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [15]:
a.argsort()

array([2, 7, 5, 3, 0, 6, 8, 1, 4, 9], dtype=int64)

In [16]:
b = np.array([5, 7, 3, 1, 10])

In [17]:
b.argsort()

array([3, 2, 0, 1, 4], dtype=int64)

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">ones() and zeros() function:</code>

* **<code style="background:yellow;color:black">ones() function</code> creates a NumPy array filled with ones. We can specify the shape of the array as a tuple, and it will create an array of the specified shape with all elements set to 1.**

* **<code style="background:yellow;color:black">zeros() function creates a NumPy array filled with zeros.</code> Like np.ones(), we can specify the shape of the array as a tuple, and it will create an array of the specified shape with all elements set to 0.**

* **These functions will create an array of all 1's and all 0's.** 

* Below code will create a np array of 1s and how many 1s will be there is provided as a parameter. All of them will be floating point numbers. Here in the example below an array of 5 number of 1s will be created. If we would have provided 7 as a parameter, 7 number of 1s would have been created.

In [18]:
a = np.ones(5)

a

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
b = np.zeros(5)

b

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">eye() function:</code>

* **The <code style="background:yellow;color:black">eye() function creates a 2D identity matrix,</code> which is a square matrix with ones on the main diagonal and zeros elsewhere. You can specify the number of rows and columns as an argument.** 

* It is often used in linear algebra and for creating transformation matrices.

* **A default sort() method implementation looks like this -- numpy.eye(N, M = None, k = 0).**

* **It takes a few following arguments:**

    * **N:** Number of rows.
    * **M:** (Optional) Number of columns. If not specified, it defaults to N.
    * **k:** (Optional) The index of the diagonal where the ones are located. The main diagonal has k = 0.

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Ufunc Sorting:</code>

* **In NumPy, a <code style="background:yellow;color:black">ufunc (universal function)</code> is a function that operates element-wise on ndarray objects. NumPy provides a variety of ufuncs to perform operations such as arithmetic, trigonometric, and logical operations on arrays efficiently.** 
* **<code style="background:yellow;color:black">Sorting in NumPy can be accomplished using ufuncs like np.sort() and np.argsort().</code>**

* NumPy provides a wide range of universal functions (ufuncs) that operate element-wise on arrays, allowing for efficient and vectorized operations. **Some common ufuncs in NumPy include:**

    * **<u>Mathematical Operations:</u>**

        * np.add: Add corresponding elements of two arrays.
        * np.subtract: Subtract elements of the second array from the first.
        * np.multiply: Multiply corresponding elements of two arrays.
        * np.divide: Divide elements of the first array by the second.
        * np.exp: Compute the exponent of each element.
        * np.log, np.log10, np.log2: Compute natural logarithm, base-10 logarithm, and base-2 logarithm, respectively.
        * np.sin, np.cos, np.tan: Trigonometric functions.
        * np.sqrt: Compute the square root of each element.
        * np.power: Raise elements of the first array to the power of the corresponding elements in the second array.

    * **<u>Statistical Functions:</u>**

        * np.mean: Compute the mean of array elements.
        * np.median: Compute the median of array elements.
        * np.std: Compute the standard deviation of array elements.
        * np.var: Compute the variance of array elements.
        * np.min, np.max: Find the minimum and maximum values in an array.
        * np.sum: Compute the sum of array elements.

    * **<u>Trigonometric Functions:</u>**

        * np.sin, np.cos, np.tan: Sine, cosine, and tangent.
        * np.arcsin, np.arccos, np.arctan: Inverse trigonometric functions.
        
    * **<u>Bitwise Operations:</u>**

        * np.bitwise_and, np.bitwise_or, np.bitwise_xor: Bitwise AND, OR, and XOR.
        * np.bitwise_not: Bitwise NOT.

    * **<u>Comparison Operators:</u>**

        * np.greater, np.greater_equal: Element-wise comparison (greater than, greater than or equal to).
        * np.less, np.less_equal: Element-wise comparison (less than, less than or equal to).
        * np.equal, np.not_equal: Element-wise comparison (equal, not equal).

    * **<u>Linear Algebra:</u>**

        * np.dot: Dot product of two arrays.
        * np.linalg.inv: Inverse of a square matrix.
        * np.linalg.det: Determinant of a square matrix.
        * np.linalg.eig: Eigenvalues and eigenvectors of a square matrix.

In [24]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

* **Here in 2D array, sorting is performed by last axis.** 

* In this case, the last axis is AXIS 1, so it will perform sorting on axis 1. Axis 1 is row wise. So, it will perform sorting row wise. Sorted version of 1st row is 4 23 43, sorted version of 2nd row is 3 12 89 ans so on.

* So, when we implement np.sort(a) where "a" is a 2D array, it will perform sorting on the basis on last axis.

In [25]:
b = np.sort(a)

b

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Element wise operations:</code>

* **<code style="background:yellow;color:black">Element-wise operations</code> in NumPy refer to operations that are performed independently on each element of an array.**
* **These operations are vectorized, meaning that they are applied to the entire array or a portion of it without the need for explicit looping. This approach is more efficient than using explicit loops and is a key feature of NumPy that contributes to its performance.**

**<u>Here are some examples of element-wise operations in NumPy:</u>**

* **<code style="background:yellow;color:black">Element-wise Arithmetic</code>**
* **<code style="background:yellow;color:black">Element-wise Comparison</code>**
* **<code style="background:yellow;color:black">Element-wise Trigonometric functions</code>**
* **<code style="background:yellow;color:black">Element-wise Logical operations</code>**

These examples demonstrate how NumPy allows us to perform operations on entire arrays or elements in a concise and efficient manner. The use of vectorized operations improves code readability and performance compared to using explicit loops.

In [26]:
arr = np.array([1, 2, 3, 4, 5])

# Addition
result_add = arr + 2  # Add 2 to each element

# Multiplication
result_mul = arr * 3  # Multiply each element by 3

# Exponentiation
result_pow = np.power(arr, 2)  # Square each element

print("Original array:", arr)
print("Result after addition:", result_add)
print("Result after multiplication:", result_mul)
print("Result after exponentiation:", result_pow)

Original array: [1 2 3 4 5]
Result after addition: [3 4 5 6 7]
Result after multiplication: [ 3  6  9 12 15]
Result after exponentiation: [ 1  4  9 16 25]


In [27]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 2, 3, 3, 5])

# Element-wise greater than comparison
result_gt = arr1 > arr2

# Element-wise equality comparison
result_eq = arr1 == arr2

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Result of greater than comparison:", result_gt)
print("Result of equality comparison:", result_eq)

Array 1: [1 2 3 4 5]
Array 2: [2 2 3 3 5]
Result of greater than comparison: [False False False  True False]
Result of equality comparison: [False  True  True False  True]


In [28]:
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2])

# Element-wise sine
result_sin = np.sin(angles)

# Element-wise cosine
result_cos = np.cos(angles)

print("Angles:", angles)
print("Sine values:", result_sin)
print("Cosine values:", result_cos)

Angles: [0.         1.57079633 3.14159265 4.71238898]
Sine values: [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]
Cosine values: [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16]


In [29]:
arr = np.array([True, False, True, False])

# Element-wise logical NOT
result_not = np.logical_not(arr)

# Element-wise logical AND
result_and = np.logical_and(arr, np.array([True, True, False, False]))

print("Original array:", arr)
print("Result of logical NOT:", result_not)
print("Result of logical AND:", result_and)

Original array: [ True False  True False]
Result of logical NOT: [False  True False  True]
Result of logical AND: [ True False False False]


**Here are some more examples of element-wise arithmetic operations in NumPy.**

In [30]:
a = np.arange(5)

a

array([0, 1, 2, 3, 4])

In [31]:
b = np.arange(5)

b

array([0, 1, 2, 3, 4])

In [32]:
a * b

array([ 0,  1,  4,  9, 16])

In [33]:
a = np.arange(1,13).reshape(3,4)

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
b = np.arange(2,14).reshape(3,4)

b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

**Element wise multiplication of 2D arrays: It will be performed element wise, means 1st element of 2D array 1 will be multiplied with 1st element of 2D array 2, 2nd element of 2D array 1 will be multiplied with 2nd element of 2D array 2 and so on, and the resulting 2D array is returned.**

In [35]:
a * b

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Matrix Multiplication:</code>

* **<code style="background:yellow;color:black">Matrix multiplication</code>in numpy is the same as we studied in school about how matrixes are multiplied i.e. matrix multiplication. This is however, different from element wise multiplication of arrays, which is seen above, and the only operator used for element wise multiplication is " <b>*</b> ".**

* **There is one important rule of matrix multiplication that number of columns of 1st matrix should be of same as number of rows of 2nd matrix.**

* **Second important rule is about the size of the resultant matrix. The number of rows of resultant matrix will be equal to number of rows of matrix 1 and columns of resultant matrix will be equal to number of columns of matrix 2.**

* For example, Let M1 be a 2 X 3 matrix, M2 be a 3 X 5 matrix. What will be the shape of the resultant matrix? - 2 X 5. Let M1 be a 2 X 4 matrix, M2 be a 2 X 4 matrix. Matrix multiplication - Not possible.

* **<code style="background:yellow;color:black">There are 3 ways of matrix multiplication in numpy:</code>**

    * np.dot() function
    * @ operator
    * np.matmul() function

Among these np.matmul is most widely used. The np.matmul() function is flexible and can handle different array shapes, including broadcasting when needed. It's a good choice for performing matrix multiplication when we have arrays with different dimensions or shapes. However, for regular 2D matrix multiplication, the @ operator and the np.dot() function are often more commonly used and are more concise.

In [36]:
a = np.arange(1, 13).reshape(3,4)

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
b = np.arange(2,14).reshape(4,3)

b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

* Can we do matrix multiplication of these two matrices? YES because number of rows of 1st matrix is equal to the number of cols of the 2nd matrix. And that can be confirmed by checking the shape of the two matrices.

* What will be the shape of the resultant matrix? - 3 X 3

In [38]:
a.shape

(3, 4)

In [39]:
b.shape

(4, 3)

In [40]:
np.dot(a,b)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [41]:
a @ b

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [42]:
np.matmul(a,b)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [43]:
A = np.arange(10).reshape(5,2)

A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
B = np.arange(2).reshape(2,1)

B

array([[0],
       [1]])

**The output is also called column vector.**

In [45]:
C = np.dot(A,B)

C

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [46]:
C.shape

(5, 1)

**<code style="background:yellow;color:black">Whats is the difference between 5,1 and 5, ?</code> 5,1 is a 2D matrix of size 5 X 1, 5 rows and 1 column. Whereas, 5, is a 1D np array having 5 elements, thats it, there is no concept of rows and columns in 1D array.**

In [47]:
d = np.arange(5)

In [48]:
d.shape

(5,)

In [49]:
len(d)

5

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Vectorization:</code>

* **<code style="background:yellow;color:black">Vectorization</code> is a fundamental concept in NumPy and other array computing libraries. It refers to the process of applying operations or functions to entire arrays or large sections of arrays at once, <u>without the need for explicit Python for-loops.</u>** 

* **Vectorization offers several advantages:**

    * **<u>Improved Performance:</u>** Vectorized operations can be significantly faster than equivalent operations implemented using Python for-loops. This is because it can take advantage of hardware-level optimizations and parallelism which refers to taking advantage of multicore processors and parallel execution.

    * **<u>Simplified Code:</u>** Vectorized code is often more concise and easier to read than equivalent code with explicit loops. This leads to more maintainable and understandable code.
    
In terminology,

1. 1d np array is called vector
2. 2d np array is called matrix
3. 3d onwards is called tensors

In [2]:
a = np.arange(1, 13)

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**Below is element wise operation of multiplication.**

In [3]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

**We can also create a function to apply some operation to all the elements of an array.**

In [4]:
def solve(x):
    
    if x % 2 == 0:  # If x is even
        x = x * 2  
    
    else:  
        x = x * 3

    return x

In [5]:
solve(5)

15

In [6]:
solve(6)

12

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

* Now, we want to apply the solve function to every element of np array "a". 

* **Approach 1** is to apply loop, select a[i] and select the solve function, call solve(a[i]) for i in range(n). But this is a slow operation. **Loops are not that fast.**

* **Approach 2 is <code style="background:yellow;color:black">numpy vectorization.</code> Vectorization will do the same thing but in a very fast way. Vectorization effectively allows us to apply element-wise to a NumPy array. How to do that?** 

* We have to create a **vectorized version** of the solve function.

### <code style="background:yellow;color:black">vectorize() function:</code>

* **In NumPy, the <code style="background:yellow;color:black">vectorize() function</code> is used to create a vectorized function from a non-vectorized (scalar) function.** 
* **A vectorized function is a function that can operate element-wise on arrays, similar to NumPy's universal functions (ufuncs). The vectorize function allows us to apply a scalar function to each element of one or more input arrays, broadcasting as necessary.** 

* By below code, we vectorize the solve function.

* So, essentially we are saying that we have created a function called solve, now we are creating a vectorized form of that function and storing it in a new function called "aj_func".

**<code style="background:yellow;color:black">Use cases of vectorization:</code>**

1. **<u>We can apply vectorizaton on any python pre defined or in-built function:</u>** Here, we are vectorizing in-built log function of the math module of python. And then we are passing the entire np array "a" to that newly defined vectorized form of log function, to get log of all the elements of "a". Basically vectorization supports element-wise operations on arrays, where the same operation is applied to each element in an array.

2. **<u>Data Manipulation:</u>** Vectorization simplifies data manipulation tasks. You can easily perform tasks like filtering, transformation, or combining arrays without writing explicit loops.

In [8]:
aj_func = np.vectorize(solve)

**This will not work because solve func is not designed to have a np array as argument.**

In [9]:
solve(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**We can pass our np array "a" to the new vectorized aj_func and it works as expected.**

In [10]:
aj_func(a)

array([ 3,  4,  9,  8, 15, 12, 21, 16, 27, 20, 33, 24])

In [11]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
import math

In [13]:
vectorized_log = np.vectorize(math.log)

In [14]:
vectorized_log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665])

In [15]:
b = np.arange(1,10).reshape(3,3)

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* **Vecorization also works on a 2D array as well.**

* Here every element is passed to the solve func and solve func does its work as required on every element individually.

In [16]:
aj_func(b)

array([[ 3,  4,  9],
       [ 8, 15, 12],
       [21, 16, 27]])

<hr style="border: 1px solid gray;">

# <code style="background:yellow;color:black">Broadcasting:</code>

* **<code style="background:yellow;color:black">NumPy broadcasting</code> is a powerful feature that allows NumPy to perform operations on arrays of different shapes, making it possible to combine and manipulate arrays that would otherwise have incompatible shapes.** 

* Broadcasting is particularly useful when we want to perform element-wise operations on arrays of different shapes without having to explicitly reshape or tile the arrays to match.

* **The key idea behind broadcasting is that when performing element-wise operations between two arrays, NumPy compares their shapes element-wise, from right to left. It starts by comparing the trailing dimensions (those with size 1 or that are missing) and then extends to the higher dimensions.**<br><br><br>

* In the first row in the image below, we are adding 2 matrices of size 4,3 so its simple element wise addition. Thats 1st element of 1st matrix is added with 1st element of 2nd matrix, 2nd element of 1st matrix is added with 2nd element of 2nd matrix and so on. So thats clear, easy and straightforward, and this is the ideal scenario.

* Now in 2nd row of the image, if we try to add these two matrices of different sizes, one of 4,3 and other of 1,3, logically it should give error, because we cant perform element wise operation on 2 different sizes. But in some specific conditions, that we will soon learn, **2ND MATRIX WILL AUTOMATICALLY REPLICATE ITSELF OR ENLARGE ITSELF TO FIT IN THE SIZE OF THE 1ST MATRIX, AND THEN ELEMENT WISE OPERATION WILL HAPPEN.** The faint image tells us exactly this.

* In 3rd case, we have one column matrix and one row matrix, both are of different sizes, so again if we try to add these two logically it should give error because we cant perform element wise operation on 2 different sizes. So what actually will happen is **1ST MATRIX WILL REPLICATE ITSELF TO MATCH FOR THE NUMBER OF COLUMNS OF 2ND MATRIX AND 2ND MATRIX WILL REPLICATE ITSELF TO FIT IN IN FOR THE NUMBER OF ROWS OF THE 1ST MATRIX, AND THEN ELEMENT WISE OPERATION HAPPENED AND WE GOT THE RESULT.** The faint image tells us exactly this. 

* Replication is done automatically. **THIS IS CALLED BROADCASTING. AND IT NOT ONLY APPLIES AUTOMATICALLY IN CASE OF ADDITION BUT ALSO APPLIES IN CASE OF MULTIPLICATION.**

* Now, to understand how and why this happened, we need to understand "tile" function. 

### <code style="background:yellow;color:black">tile() function:</code>

* **In NumPy, the <code style="background:yellow;color:black">tile() function</code> is used to construct an array by repeating a given array (or a list) a certain number of times along specified axes. This function is useful for creating larger arrays by replicating smaller arrays along specified dimensions.**

* **In tile func, we pass 2 arguments: one the array, in our case "a", and a tuple containing the information about how many times we want to replicate the array "a" horizontally and vertically, or how many instances of the array we want horizontally and vertically.** 

* In our case, we passed a tuple (3,1). This means replicate the array "a" or we want to create instances of the array such that in total it becomes 3 times horizontally. And replicate the array or create instances of the array such that it becomes 1 time vertically. So, we get the array having 3 rows and 4 columns because originally the array had 1 row and 4 columns.

* **Here not to confuse (3,1) with the size of the resultant array. Its how many times we want to replicate the array or how many instances of the array we want horizontally and vertically.**

* Please note that in tile func, if we pass array itself as the first argument and run it again and again, everytime the resultant array will be replicated again and again so that the result will inrease in size. Thats why we dont pass array as the first argument in tile func, instead we pass arange() so that everytime array will be generated as new and even if we we run this tile func again and again resultant array will be same everytime, it wont grow.

![bro.jpg](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/047/364/original/download.jpeg?1694345633)

In [3]:
a = np.arange(0, 40, 10)

a

array([ 0, 10, 20, 30])

In [4]:
a = np.tile(a, (3, 1))

a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [5]:
b = np.arange(0, 3)

b

array([0, 1, 2])

In [6]:
b = np.tile(np.arange(0, 3), (4, 1))

b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

**Now, can we perform a + b? Element wise addition? - NO. Because shape of b is 4,3 and shape of a is 3,4. So, we can do transpose of a to get shape of a as 4,3. Now we can do a + b to get element wise addition.**

In [7]:
b.shape, a.shape

((4, 3), (3, 4))

In [8]:
a = a.T

In [9]:
b.shape, a.shape

((4, 3), (4, 3))

In [10]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [11]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [12]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [13]:
b = np.arange(0, 3)

b

array([0, 1, 2])

In [14]:
a.shape, b.shape

((4, 3), (3,))

In [15]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [16]:
b

array([0, 1, 2])

* Now, what will happen if we do a + b? As we learnt earlier, replication of 2nd array i.e. "b" will happen and then element wise addition will happen automatically.

* **There is a <code style="background:yellow;color:black">RULE</code> according to which this replication happens.**

**We will understand whether broadcasting will be performed between 2 given np arrays or not.** 

**Lets take 2 np arrays of size (4,3) and (3,).** 
* What is the dimension of both the arrays? 
* 1st array is 2D and 2nd array is 1D. 
* So, first of all **MENTALLY** make 2nd array same dimension as 1st array, in our case we will make 2nd array as a 2D array. 
* How will we do it?
* **WE WILL ALWAYS ADD THE MISSING DIMENSION AS "1" TO THE LEFT SIDE.**
* **HERE WE WILL VISUALIZE (3,) AS (1,3).**
* **<code style="background:yellow;color:black">SO OUR RULE SAYS - ALWAYS MAKE BOTH ARRAYS SAME DIMENSION BY PADDING THE ARRAY WITH "1" ON THE LEFT SIDE.</code>**
* REFER NOTES FOR MORE CLARITY.
* No matter how many dimensions to add, make it all 1s from the left.

**Now lets take two 2D arrays of size (4,3) and (1,3).** 
* Now from the right side go one by one and compare. 
* **REFER NOTES FOR MORE CLARITY.** 
* So here, we will compare right most dimension 3 of (4,3) to rightmost dimension 3 of (1,3). 
* There are 2 things to check. 
* First, whether they are same or not. 
* Second, atleast one of them should be "1". 
* If any of these two condition is satisfied in comparison, then that dimension is good to go. 
* **Similarly, compare each and every dimesnion and if every dimension is good to go, <code style="background:yellow;color:black">THEN BROADCASTING WILL BE PERFORMED OTHERWISE NOT.</code>**

**Lets take another example.** 
* Lets take 2 np arrays as shown in last row of the image. 
* Shape of 1st array is (4,1) its a 2D array. 
* Shape of 2nd array is (3,) its a 1D array. 
* **REFER NOTES FOR MORE CLARITY ON THIS AND <code style="background:yellow;color:black">DIFFERENCE BETWEEN 1D AND 2D ARRAYS.</code>**
* Now lets see if broadcasting will be performed or not as per our rule. 
* a is of shape (4,1) and b is of shape (3,). 
* So we imagine b as (1,3) as explained in above example. 
* Now check and compare rightmost dimesnions of both arrays i.e 1 of a and 3 of b. 
* We see it satisfies our condition of atleast one of them should be "1", so good to go. 
* **Similarly 2nd dimension is also compared and found good to go. So, <code style="background:yellow;color:black">BROADCASTING WILL BE DONE.</code>**  

**After performing broadcasting, the shape of the resultant array will be maximum of both the arrays's dimension.**

In above example it will be (4,3). 

In [17]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [18]:
a = np.arange(0, 40, 10).reshape(4, 1)

a

array([[ 0],
       [10],
       [20],
       [30]])

In [19]:
b = np.arange(0, 3)

b

array([0, 1, 2])

In [20]:
a.shape, b.shape

((4, 1), (3,))

In [21]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

* Here in the below example, lets compare shape of a is (2,4) with that of b (4,4). 
* Rightmost dimension satisfies the condition that values should be same, so its good to go. 
* But, next dimesnion i.e. 2 and 4 doesnt satisfy both the conditions, that is values should be same or atleast one of them should be "1", so its not good to go. 
* **Hence, <code style="background:yellow;color:black">OVERALL BROADCASTING WILL NOT OCCUR, and a + b will throw an error.</code>** 

In [22]:
a = np.arange(8).reshape(2, 4)

a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
b = np.arange(16).reshape(4, 4)

b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
a.shape, b.shape

((2, 4), (4, 4))

In [25]:
a + b

ValueError: operands could not be broadcast together with shapes (2,4) (4,4) 

* In the below example, broadcasting will be done and two np arrays will be multiplied. 
* **Basically, -1,0,-1 is getting replicated horizontally to make it a total 3 times, and then element wise multiplication happens.**

In [26]:
A = np.arange(1, 10).reshape(3, 3)

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
B = np.array([-1, 0, 1])

B

array([-1,  0,  1])

In [28]:
A * B

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

**Another example.**

In [29]:
A = np.arange(12).reshape(3, 4)

B = np.array([1, 2, 3])

A + B

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

### <code style="background:yellow;color:black">Quiz</code>

Given two arrays of shape

1. Array A of shape  (8, 1, 6, 1)
2. Array B of shape (7, 1, 5)

Is broadcasting possible in this case? If yes, what will be the shape of output ?

* Broadcasting not possible as dimensions don't match
* Broadcasting not possible as dimension value 6 and 5 doesn't match
* Broadcasting possible. Shape will be (8, 1, 6, 5)
* Broadcasting possible; Shape will be (8, 7, 6, 5)

**<code style="background:yellow;color:black">Answer will be D. Refer notes.</code>** 

### <code style="background:yellow;color:black">Doubts:</code>

In [40]:
a = np.array([[4,2],
             [1,5]])

a

array([[4, 2],
       [1, 5]])

**Sorting the 2D array w.r.t. axis 0 in ascending order, that is column wise.**

In [41]:
np.sort(a, axis = 0)

array([[1, 2],
       [4, 5]])

**Sorting in descending order.**

In [44]:
# Sort the copied array along axis 0 in descending order
b = np.sort(a, axis = 0)
c = b[::-1]

print("Original array:")
print(a)
print("Sorted array:")
print(c)

Original array:
[[4 2]
 [1 5]]
Sorted array:
[[4 5]
 [1 2]]


**Sorting the 2D array w.r.t. axis 1 in ascending order, that is row wise.**

In [45]:
np.sort(a, axis = 1)

array([[2, 4],
       [1, 5]])